### ISSUE TITLE
git tag wilc_linux_15_3_2 missing

### ISSUE THREAD

**Issue by fsa-ableton** [linux4wilc/firmware#11]
Hello,

What happened to the release tag wilc_linux_15_3_2 ?
Can you please point me to the newest stable release tag?

Thanks and regards,
F. Sauter

**Comment by AdhamAbozaeid** [comment]
Hi @fsa-ableton 
This tag was moved to wilc_linux_15_3_rc2 since it was a pre release.
Latest release is wilc_linux_15_3_1.
You can see a list or releases/pre-releases [here](https://github.com/linux4wilc/firmware/releases)

**Comment by fsa-ableton** [comment]
Thank you! :)
