### ISSUE TITLE
15.2 release notes missing

### ISSUE THREAD

**Issue by tsifb** [linux4wilc/firmware#5]
Readme.md doc does not include a link to release notes.

The recently updated readme.md file in the driver repo dev branch (which includes a link to release notes) points to an older release notes doc. (http://ww1.microchip.com/downloads/en/DeviceDoc/WSGA-3295A.pdf)

Can the 15.2 release notes doc be linked here, or the document added to the repo or this issue?

**Comment by AdhamAbozaeid** [comment]
The release notes link will be updated once the document is available on the Microchip product pages.
https://www.microchip.com/wwwproducts/en/ATWILC1000
https://www.microchip.com/wwwproducts/en/ATWILC3000
which should happen in the coming few days.
I'll keep you notified once it's there.

**Comment by tsifb** [comment]
OK great - thank you!
