### ISSUE TITLE
WILC1000 firmware floods packets when multiple stations are connected to third party AP

### ISSUE THREAD

**Issue by tsifb** [linux4wilc/firmware#6]
# Summary

The WILC1000 module is occasionally transmitting large volumes of erroneous packets in bursts even when a device should be almost completely idle. The problem is particularly more prevalent when more than one WILC1000 devices are associated with the same AP as if they are interacting with each other, and trigger this condition.

The setup is a TP-link or Netgear AP, with WILC1000 modules on custom PCBs connected to SAMA5D42 running linux kernel 4.9.52 and the linux4wilc driver.

The WILC1000 modules are configured only as Stations. (no AP is configured in the WILC1000)

The problem has been initially observed as intermittent poor throughput when loading ~100MB root filesystem images into the custom PCB over Wi-Fi. The problem appears to be much worse when multiple units are operating, even when only loading the file into one unit at a time.

We have made a very detailed analysis of the Wi-Fi behaviour, including using an independent Wi-Fi packet capture device (sniffer), a spectrum analyser, and monitoring the WILC1000 supply current to see when it transmits.

# Analysis

1. With two devices (or more) connected to the same AP, if either device is generating even a small amount of traffic (i.e. transmitting), then both devices begin rapidly transmitting very significant amounts of traffic when they should be transmitting essentially nothing and sitting idle.
   1. The devices have been verified as transmitting by watching the VBATT supply current using an oscilloscope across a shunt resistor.
      1. Inspection of the oscilloscope waveform show very clearly when a WILC 1000 is transmitting.
   1. Using a Wi-Spy DBx spectrum analyser, the rapid transmitting can be observed.
      1. Typically there will be a burst of rapid transmission that lasts for 10-12 seconds, and can be often followed by shorter (0.5-1s) burst approximately 1-2 seconds after the longer burst. 
   1. The data transmitted has been captured using a Wi-Fi sniffer (rtl8812au usb Wi-Fi  adapter + wireshark (802.11 + radio tap ) + kali linux)
      1. The packets captured record the RSSI in the radio tap header. 
      1. The physical organisation of AP and stations have (significantly) different rssi values at the sniffer.
      1. This gives a per packet record of which device actually transmitted a packet, irrespective of the MAC addresses included in the packet.
   1. Using the Wi-Fi sniffer packet capture, many thousands of irrelevant packets are received
      1. Packets are largely correctly formatted, with correct checksums.
      1. Packets are mostly decoded in wireshark as CF-END frames, although some other almost instantaneous retry packets have also been observed.
      1. Some of the erroneous CF-END packets have invalid 00:00:00:00:00:00 source address (BSSID)
      1. Some of the erroneous CF-END packets have invalid 00:00:00:00:00:00 destination address (RA)
      1. Some of the erroneous CF-END packets have both invalid source and invalid destination addresses of 00:00:00:00:00:00
   1. Some of the erroneous CF-END packets have the access point address in either or both source or destination.
      1. We have absolutely proven without doubt that even though the source MAC address in these packet indicates the source MAC of the AP, it has been transmitted my the WILC1000 station.
      1. The captured packet's RSSI iu the radio tap header can only be that of a WILC1000, not the AP.
         1. The Wi-Spy Spectrum analyser shows the signal strength that can only be the WILC1000
         1. The VBATT current on the oscilloscope shows the WILC 1000 is transmitting during this period
   1. CF-END frames should only be transmitted by the AP (PCF) and contain the AP MAC as source (BSSID) and broadcast address as RA.
   1. During this time throughput performance of the drops significantly / ping packets are significantly delayed
1. WILC 1000 Devices are running in STA mode only. (no AP is configured)
1. Problem occurs with both a TP-Link Archer C20 or a Linksys WRT ACS-1900 as the access point.
   1. With the Linksys, problem appears slightly less prevalent.
1. Problem occurs at intermittent intervals - when just a simple 1s ping from one device to  the AP, the problem might occur after a few minutes, and last for 10-12 seconds. (TP-link AP is more frequent)
1. Problem starts once module connects to AP (i.e. driver, module is up, firmware is loaded and wpa_supplicant running)
   1. Problem does NOT stop when driver is stopped and kernel module is removed from kernel - i.e. firmware is still running independent of host.
   1. Problem only stops once kernel driver is reloaded AND firmware is reloaded i.e. once WILC1000 is reset/restarted.
1. Problem occurs when using an Microchip (Atmel) SAMA5D4XULT dev board with a Rev 4 WILC1000-SD dev board and wilc_demo image i.e. solely Microchip hardware and firmware.
1. With only one WILC1000 unit running, the problem is much less prevalent
   1. There are still numerous Wi-Fi retries similar to: https://github.com/linux4wilc/driver/issues/25
1. With multiple WILC100 stations connected, the network becomes almost useless, with very frequent periods of extremely low throughput. (6 stations for example)
1. Versions:
   1. WILC1000 firmware: 15.2 RC2
   1. linux4wilc driver: commit hash 06108eeb4beb070d2ed870c2ac86aeb65b5c6da0 from -dev branch

# Packet Capture file notes:
### Setup:
* Multiple WILC1000 stations connected to TP-Link Access Point.
* Packet sniffer (RTL8812AU + Wireshark on Kali linux) located very close to WILC1000 MAC f8:f0:05:d0:9f:22
* AP and Other WILC1000 stations located several meters away from above WILC1000
* This setup provides VERY clear indication of when 9f:22 transmits because Radiotap header contains the signal strength.
* Observation of typical (normal) packets in the capture logs show RSSI values for various transmitters at the packer sniffer
   * e.g. Beacon Frames sent from AP show typical basic rate RSSI value.
   * e.g NULL data frames or QOS-Data frames show RSSI from 9f:22.

### Filename: [multiplewilc1000-no-traffic.zip](https://github.com/linux4wilc/driver/files/2771431/multiplewilc1000-no-traffic.zip)
Multiple WILC1000 stations connected to AP, with no other additional higher level traffic (no pings, no iperf, no file transfers)

Frame 54: This is correct addressing for CF-END frame, however most probably send from Other WILC1000 due to -82dBm signal strength, and is out of context (no other PCF packets seen)

Frame 55: First Erroneous CF-End Frame.
* Radio Tap Header Antenna Signal = -24dBm indicating it is transmitted from WILC1000 (MAC: f8:f0:05:d0:9f:22) located a few cm from sniffer.
* time delta from F54 is 0.000001003s
* Source MAC address is not correct - this MAC is the AP's MAC
* Destination MAC is not correct, this is the AP's MAC - and for a CF-END frame, it should be broadcast address

Frame 56: Second Erroneous CF-End frame.
* Again rssi is -24dbm - sent from 9f:22 WILC1000
* time delta from F55 is 0.000000620

Frame 57: Third Erroneous CF-End frame, however is sent my another WILC1000.
* RSSI is -80dBm - much weaker signal, around that observed from other WILC1000.
* Incorrect addressing.

Frames 58 - 1893: alternating erroneous CF-End frames transmitted by WILC1000 unit, as seen by inspecting rssi values.
* A very large block of frames - should never be seem in normal PCF operation.
* each frame is transmitted in very rapid succession, as seem by inspecting the packet delta times.
* elapsed time from frame 52-1893 = 0.332s / Frames transmitted at average of 5545 pkts/s.

Throughout the rest of the capture log:
* bursts of erroneous CF-End frames are observed.

### Filename: [singlewilc1000-iperf-udp30M.zip](https://github.com/linux4wilc/driver/files/2771436/singlewilc1000-iperf-udp30M.zip)
Packet capture of a single WILC1000 sending UDP frames from iperf.

When  comparing the previous packet capture with a single WILC1000 connected to the SAME Access Point, the blocks of rapidly repeating CF-End frames do not occur, and observed file transfer throughput is much higher, although still not as high as should be possible.

There are lots of re-transmitted frames. for example, Frames 91 and 92 are re-transmissions of Frame 90.

Frame 93: Decodes as a CF-End frame, however is transmitted by the WILC1000 station. CF-End should only be sent from the AP. Note: RSSI is -26dBm, so must have been transmitted by WILC1000

CF-End frames are transmitted by WILC1000, however there are no other PCF packets sent. This indicates that PCF function is not being used, however WILC1000 seems to be transmitting CF-End frames.

# Conclusion
When Mulitple WILC1000 Stations are close, they trigger each other's firmware into transmitting junk packets very rapidly. A single WILC1000 will not flood the network, however does send incorrect junk frames and will re-transmit many otherwise valid frames, sometimes so quickly that an acknowledgement can not have been received.

This issue renders the WILC1000 unusable, or at best - when a single Station is used - poor performance.

We have spent considerable engineering resources on investigation of this and other previous WILC1000 issues. We require urgent and dedicated attention from Microchip engineers to fix this serious issue.

A Salesforce issue will be opened referencing this report.

**Comment by ZonKnoZ** [comment]
@AdhamAbozaeid , here we go:
1. ti AM3352 CPU based board similar to Beaglebone Black running on ti-processor-sdk-linux-am335x-evm-04.02.00.09 (that is linux-4.9.59+gitAUTOINC+a75d8e9305-ga75d8e9305).
2. the drivers & firmware were downloaded last friday 15p.m. CET from the dev branches respectively.
3. modprobe wilc_spi
4. service hostapd start
with hostapd.conf:
>interface=wlan0
>hw_mode=g
>channel=3
>ieee80211d=1
>country_code=DE
>ieee80211n=1
>wmm_enabled=1
>auth_algs=1
>wpa=2
>wpa_key_mgmt=WPA-PSK
>rsn_pairwise=CCMP
>ssid=test123
>wpa_passphrase=test123!

Then I just connect a tablet to the AP and start to stream a youtube video. Freeze comes after a while.

Btw. I'm aware that this is a bleeding edge test case here + I use a WILC3000 , so sorry but can't test it.

**Comment by AdhamAbozaeid** [comment]
@ZonKnoZ , Do you see the same issue with the master, or on the dev only? Do you have the driver/FW logs?
Also, please open a new ticket for this one, since it's not related to the CF End packets problem

**Comment by tsifb** [comment]
We have built in the build 11050 firmware and are testing.
So far, initial observation is that the flood of CF-END does not occur.
Now testing with more units powered on, and using our typical application use-case.

@AdhamAbozaeid Are there additional issues / fixes that you are aware of that will be included in the next release?

**Comment by AdhamAbozaeid** [comment]
Most of the changes will be in the driver to align with WILC's driver on the kernel staging tree, in addition to:
Fix for issue https://github.com/linux4wilc/driver/issues/21
Improvement of data transfer in concurrent STA/AP mode
Fix for failures when CFG80211 PS (CONFIG_CFG80211_DEFAULT_PS) is enabled by default issue https://github.com/linux4wilc/driver/issues/28

**Comment by tsifb** [comment]
@AdhamAbozaeid My question was about the next firmware release, although if there are driver changes that need to also be included at the same time - that would be useful to know.

I am trying to assess which combinations we should be focusing on testing, and how much effort to burn on them.

I see there are a bunch of new driver dev branch commits. We are also working in integrating these into our latest internal dev branch, which is on a slightly newer linux kernel.
We do not want to change too much - so we can retest as close as possible to the original setup to provide quality feedback to you, however our eventual target will include a newer kernel and important wilc driver updates.

Your input would be helpful on this.

As part of the testing, we will be carefully observing the debug output  from the driver and WILC module serial port - if we notice anything suspicious, we will open new issues here to get your feedback.

**Comment by tsifb** [comment]
Testing Update: Yesterday with 5 units connected to the AP has shown a large improvement in usability. I do have some concerns about performance where the AP to Station signal strength is lower (~-75dBm) - the throughput drops more than I expected, even at the reduced data rate. More investigation is needed here. 

Also the ability to maintain a somewhat usable ssh connection to one unit, while a file transfer / iperf is operating with another unit is not what I expect. It seems like the file transfer (TP-link AP-> WILC Station) does significantly delay packets to other units (on the order  of several seconds to 10s of seconds.)
This may impact our factory use-case, where commands need to be remotely executed in units, while others are downloading large firmware images. This may be a separate issue, but I thought it was worth mentioning early.

Further testing in the next few day:
1, more units + throughput to one unit
2, more units + multiple concurrent high throughput operations ( file transfers )
3, more units + remote shell + file transfers
4, concurrent WILC AP and WILC STA operation on one unit.
5, testing latest driver dev branch + linux kernel 4.14
During this testing we will be trying to get an understanding of reliability as well. (Power cycling in our end use application is a very rare event, and is difficult to perform)

**Comment by AdhamAbozaeid** [comment]
WILC FW and driver releases are always aligned.
So far, the changes done on top of 15.2 for the driver and firmware are independent, so you can use the fix for this issue with the driver from 15.2, without having to integrate driver changes from the dev branch

**Comment by tsifb** [comment]
@AdhamAbozaeid did you build a new WILC3000 binary set too? @Mateusz-Gwara may be able to test as well?

@Mateusz-Gwara we would appreciate your eyes on this new firmware too, if that is possible ;)

**Comment by tsifb** [comment]
@AdhamAbozaeid ok. thanks for that information.

**Comment by AdhamAbozaeid** [comment]
@tsifb , I just added the WILC3000 FW as well to my comment above

**Comment by tsifb** [comment]
I still observe some CF-End frames being transmitted by the WILC module.
I do not see the large bursts of CF-End frames.
See attached file.
As before, the Source address is not the WILC MAC, however based on the signal strength, they must be tx'ed by the WILC module. I do not believe these are legitimate packets.

[cfend-11050-sta-only.zip](https://github.com/linux4wilc/firmware/files/2934857/cfend-11050-sta-only.zip)

**Comment by AdhamAbozaeid** [comment]
@tsifb , these CF-end packets are legitimate. It's used by STAs to indicate the truncation of an obtained TXOP. You can refer to the "Truncation of TXOP" section int he 802.11

**Comment by tsifb** [comment]
Ok, so.... if I disable RTS/CTS by setting the rts threshold to 2346, will I still see the CF-End frames?
I'm assuming these are used to signal an early end to the period allocated by RTS/CTS, is that correct?

**Comment by tsifb** [comment]
@AdhamAbozaeid I noticed the binaries recently added to dev branch have a different build number to the binary you attached here for testing.
Build: 11050 vs 11064M

Are there additional changes? 
Should we move to the dev branch version to continue testing?
What does the "M" suffix mean?

**Comment by AdhamAbozaeid** [comment]
No, TXOP is different from RTS/CTS

**Comment by AdhamAbozaeid** [comment]
The binary provided in this thread (11050) is 15.2 + the fix for this issue. The fix on the dev branch has other fixes on top of 15.2
The engineering release that will be provided through salesforce will be 15.2+ fix for this issue only, same as 11050

**Comment by tsifb** [comment]
ok yes, I understood that 11050 just fixed this issue.
but your answer is confusing - can you clarify?

I was referring to the last dev commit a few days ago https://github.com/linux4wilc/firmware/commit/d66a52f675069d5527859c9085b7898d50ae1282
which appears to have build number 11064M, and the commit comment says the cf end fix is included.
Your previous comment confuses us because you implied this CF-end fix is not included.

I'm expending resources testing this firmware. I need to understand which binary we should be using so that we don't have to waste time.

My assumption is that 11064M = 15.2 release + CF END fix (as per 11050) + something else.
Is this correct?
What is the "something else"? 
Is 11064M going to be closer to your next (15.3?) release version?

I would prefer to be close as possible to the next release candidate - so if 11064M has additional fixes, this is of interest.

**Comment by AdhamAbozaeid** [comment]
I mean that the fix on the dev. branch **has the fix for cf-end** along with other fixes on top of 15.2
d66a52f has release 15.2 (2342582) + 5ca0dc2+ CF-End bug fix.
5ca0dc2 is a modification to move initialization code from the driver to the FW.

The engineering release that we are currently running sanity QA on will be release 15.2 + CF-End fix to minimize the changes and avoid introducing further bugs since we don't run full QA on engineering releases. This engineering release will be available in 2~3 weeks through salesforce for users who don't want to wait till the official release is ready.
Release 15.3 will be the first official release that has this fix, and is planned for July time frame

**Comment by tsifb** [comment]
@AdhamAbozaeid ok great, thanks for the clarification and timings. That helps us a lot.
Also as a heads up, I am going to open a new issue to discuss another observation we have made during testing, however the results for 11050 build with respect to this issue are good. 
We see much better operations when concurrently updating firmware images (~100MB) in 7 units in the same location, and have not seen any other reliability issues with this combination of firmware and driver so far.

@Mateusz-Gwara I recommend you try the wilc3000 binaries linked above if you haven't been done so already.

**Comment by Mateusz-Gwara** [comment]
I ran the driver ( a65d074 ) and firmware ( d66a52f  ) from the latest dev branch commits respectively.
The units I ran it on, were running kernel 4.9.59 as I already described above.
Unfortunately all test units ended up in a “semi-frozen” state where “ifconfig” would hang and a normal reboot would hang as well.
As our devices initially load a hostapd config, they perform a “service hostapd restart”.
This is what comes up then:

    [  151.018370] Unable to handle kernel NULL pointer dereference at virtual address 00000010
    [  151.026957] pgd = da4f4000
    [  151.029799] [00000010] *pgd=9ce91831, *pte=00000000, *ppte=00000000
    [  151.036579] Internal error: Oops: 17 [#1] ARM
    [  151.041122] Modules linked in: wilc_spi(C) cfg80211 rfkill xt_TCPMSS xt_tcpudp iptable_filter ipt_MASQUERADE nf_nat_masquerade_ipv4 iptable_nat nf_conntrao
    [  151.081654] CPU: 0 PID: 3969 Comm: hostapd Tainted: G         C      4.9.59casenio-ga75d8e9305 #4
    [  151.090902] Hardware name: Generic AM33XX (Flattened Device Tree)
    [  151.097250] task: da48f1c0 task.stack: dca5a000
    [  151.102105] PC is at get_key+0x5c/0xc4 [wilc_spi]
    [  151.107055] LR is at get_key+0x40/0xc4 [wilc_spi]
    [  151.111961] pc : [<bf12805c>]    lr : [<bf128040>]    psr: 60000013
    [  151.111961] sp : dca5bcd8  ip : 00000000  fp : bf27378e
    [  151.123931] r10: dc820000  r9 : da4e2000  r8 : 00000000
    [  151.129372] r7 : dc9fc900  r6 : 00000000  r5 : 00000002  r4 : da4e2280
    [  151.136184] r3 : 00000000  r2 : da48f1c0  r1 : c0a152f0  r0 : da4e2288
    [  151.142989] Flags: nZCv  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment none
    [  151.150424] Control: 10c5387d  Table: 9a4f4019  DAC: 00000051
    [  151.156410] Process hostapd (pid: 3969, stack limit = 0xdca5a210)
    [  151.162764] Stack: (0xdca5bcd8 to 0xdca5c000)
    [  151.167309] bcc0:                                                       60000013 dc9fc900
    [  151.175841] bce0: 00000000 c0163e4c c0a39cb4 00000002 00000000 dca5bd60 bf128000 bf224f9c
    [  151.184370] bd00: 00000000 dca5bd24 bf21fd48 c0610d58 da605014 da4e2280 0000000c bf263734
    [  151.192886] bd20: 00000002 dc9fc900 00000000 00000002 00000004 bf26c5cc bf263734 de3bc814
    [  151.201416] bd40: dc8daa80 00000000 00000014 da397400 00000000 c0577e08 bf2630c4 00000000
    [  151.209940] bd60: 386d4420 00000f72 de3bc800 de3bc810 de3bc814 da397400 da4e2000 dc820000
    [  151.218475] bd80: de3bc800 00000000 c0577be0 dc8daa80 dca5bdcc 00000001 00000000 c0577128
    [  151.227010] bda0: c0a57448 dc8daa80 00000024 dc8daa80 dca5bdcc c0577bcc de1e7000 dcd30c00
    [  151.235549] bdc0: 00000024 c0576a78 00000001 7fffffff 00000008 00000000 dc8daa80 00000024
    [  151.244075] bde0: dcd30c00 00000000 dca5bf68 c0576ecc be86fc88 00000001 dca5bf68 dca5a000
    [  151.252603] be00: 00000000 de280e80 00000000 00000f81 00000000 00000000 be86fcc0 dca5bf68
    [  151.261129] be20: 00000000 00000000 d4236480 c0107704 dca5be50 00000000 00067cc8 c052edd4
    [  151.269659] be40: dca5bf68 c052f910 00000001 00000000 da48f1c0 c0166b54 b2b2929f 14a58638
    [  151.278193] be60: 00000000 00000050 da48f668 00000000 0009a980 00000024 00000000 c12100e4
    [  151.286724] be80: da48f1c0 c0166b54 1db89764 17cc08f3 00000000 da48f668 da48f660 00000000
    [  151.295260] bea0: 00000000 c0a5f494 60000013 c0168538 00000010 00000000 00000000 d44a8f8c
    [  151.303792] bec0: 00000000 00000000 00000000 c0a5f494 60000013 c0168538 00000001 00000000
    [  151.312319] bee0: 00000000 00000000 00000000 c0a17754 00000000 00000000 00000002 c0a5f494
    [  151.320857] bf00: 60000013 c0168538 00000000 00000000 00000000 c0255350 00000000 00000000
    [  151.329391] bf20: c0233cb0 c017abcc c0a5eabb de012600 00000000 be86fc70 00000000 d4236480
    [  151.337929] bf40: 00000128 c0107704 dca5a000 00000000 00067cc8 c05306ac 00000000 00000000
    [  151.346463] bf60: 00000000 fffffff7 dca5beb0 0000000c 00000001 00000000 00000000 dca5be78
    [  151.354990] bf80: 00000000 dca5a000 00000000 00000000 00000000 00000000 00097e58 00096c90
    [  151.363521] bfa0: b6edb000 c0107560 00097e58 00096c90 00000005 be86fc70 00000000 00000000
    [  151.372057] bfc0: 00097e58 00096c90 b6edb000 00000128 000303ad 00096e00 00097ba0 00067cc8
    [  151.380596] bfe0: be86fc70 be86fc58 b6eccd17 b6cfaffc 40000010 00000005 9eff6861 9eff6c61
    [  151.389849] [<bf12805c>] (get_key [wilc_spi]) from [<bf224f9c>] (nl80211_get_key+0x1fc/0x430 [cfg80211])
    [  151.400107] [<bf224f9c>] (nl80211_get_key [cfg80211]) from [<c0577e08>] (genl_rcv_msg+0x228/0x3dc)
    [  151.409456] [<c0577e08>] (genl_rcv_msg) from [<c0577128>] (netlink_rcv_skb+0xbc/0xe0)
    [  151.417625] [<c0577128>] (netlink_rcv_skb) from [<c0577bcc>] (genl_rcv+0x20/0x34)
    [  151.425434] [<c0577bcc>] (genl_rcv) from [<c0576a78>] (netlink_unicast+0x160/0x1f0)
    [  151.433419] [<c0576a78>] (netlink_unicast) from [<c0576ecc>] (netlink_sendmsg+0x2f8/0x370)
    [  151.442052] [<c0576ecc>] (netlink_sendmsg) from [<c052edd4>] (sock_sendmsg+0x14/0x24)
    [  151.450225] [<c052edd4>] (sock_sendmsg) from [<c052f910>] (___sys_sendmsg+0x1ec/0x200)
    [  151.458476] [<c052f910>] (___sys_sendmsg) from [<c05306ac>] (__sys_sendmsg+0x40/0x6c)
    [  151.466657] [<c05306ac>] (__sys_sendmsg) from [<c0107560>] (ret_fast_syscall+0x0/0x1c)
    [  151.474929] Code: e3130010 1a000011 e0840105 e5903590 (e5932010) 
    [  151.481811] ---[ end trace 54605407682fda2c ]---
    
    Message from syslogd@89490200001095386101 at Mar 13 14:14:13 ...
     kernel:[  151.036579] Internal error: Oops: 17 [#1] ARM
    
    Message from syslogd@89490200001095386101 at Mar 13 14:14:13 ...
     kernel:[  151.156410] Process hostapd (pid: 3969, stack limit = 0xdca5a210)
    
    Message from syslogd@89490200001095386101 at Mar 13 14:14:13 ...
     kernel:[  151.162764] Stack: (0xdca5bcd8 to 0xdca5c000)
    
    Message from syslogd@89490200001095386101 at Mar 13 14:14:13 ...
     kernel:[  151.167309] bcc0:                                                       60000013 dc9fc900
    
    Message from syslogd@89490200001095386101 at Mar 13 14:14:13 ...
     kernel:[  151.175841] bce0: 00000000 c0163e4c c0a39cb4 00000002 00000000 dca5bd60 bf128000 bf224f9c
    
    Message from syslogd@89490200001095386101 at Mar 13 14:14:13 ...
     kernel:[  151.184370] bd00: 00000000 dca5bd24 bf21fd48 c0610d58 da605014 da4e2280 0000000c bf263734
    
    Message from syslogd@89490200001095386101 at Mar 13 14:14:13 ...
     kernel:[  151.192886] bd20: 00000002 dc9fc900 00000000 00000002 00000004 bf26c5cc bf263734 de3bc814
    
    Message from syslogd@89490200001095386101 at Mar 13 14:14:13 ...
     kernel:[  151.201416] bd40: dc8daa80 00000000 00000014 da397400 00000000 c0577e08 bf2630c4 00000000
    
    Message from syslogd@89490200001095386101 at Mar 13 14:14:13 ...
     kernel:[  151.209940] bd60: 386d4420 00000f72 de3bc800 de3bc810 de3bc814 da397400 da4e2000 dc820000
    
    Message from syslogd@89490200001095386101 at Mar 13 14:14:13 ...
     kernel:[  151.218475] bd80: de3bc800 00000000 c0577be0 dc8daa80 dca5bdcc 00000001 00000000 c0577128
    
    Message from syslogd@89490200001095386101 at Mar 13 14:14:13 ...
     kernel:[  151.227010] bda0: c0a57448 dc8daa80 00000024 dc8daa80 dca5bdcc c0577bcc de1e7000 dcd30c00
    
    Message from syslogd@89490200001095386101 at Mar 13 14:14:13 ...
     kernel:[  151.235549] bdc0: 00000024 c0576a78 00000001 7fffffff 00000008 00000000 dc8daa80 00000024
    
    Message from syslogd@89490200001095386101 at Mar 13 14:14:13 ...
     kernel:[  151.244075] bde0: dcd30c00 00000000 dca5bf68 c0576ecc be86fc88 00000001 dca5bf68 dca5a000
    
    Message from syslogd@89490200001095386101 at Mar 13 14:14:13 ...
     kernel:[  151.252603] be00: 00000000 de280e80 00000000 00000f81 00000000 00000000 be86fcc0 dca5bf68
    
    Message from syslogd@89490200001095386101 at Mar 13 14:14:13 ...
     kernel:[  151.261129] be20: 00000000 00000000 d4236480 c0107704 dca5be50 00000000 00067cc8 c052edd4
    
    Message from syslogd@89490200001095386101 at Mar 13 14:14:13 ...
     kernel:[  151.269659] be40: dca5bf68 c052f910 00000001 00000000 da48f1c0 c0166b54 b2b2929f 14a58638
    
    Message from syslogd@89490200001095386101 at Mar 13 14:14:13 ...
     kernel:[  151.278193] be60: 00000000 00000050 da48f668 00000000 0009a980 00000024 00000000 c12100e4
    
    Message from syslogd@89490200001095386101 at Mar 13 14:14:13 ...
     kernel:[  151.286724] be80: da48f1c0 c0166b54 1db89764 17cc08f3 00000000 da48f668 da48f660 00000000
    
    Message from syslogd@89490200001095386101 at Mar 13 14:14:13 ...
     kernel:[  151.295260] bea0: 00000000 c0a5f494 60000013 c0168538 00000010 00000000 00000000 d44a8f8c
    
    Message from syslogd@89490200001095386101 at Mar 13 14:14:13 ...
     kernel:[  151.303792] bec0: 00000000 00000000 00000000 c0a5f494 60000013 c0168538 00000001 00000000
    
    Message from syslogd@89490200001095386101 at Mar 13 14:14:13 ...
     kernel:[  151.312319] bee0: 00000000 00000000 00000000 c0a17754 00000000 00000000 00000002 c0a5f494
    
    Message from syslogd@89490200001095386101 at Mar 13 14:14:13 ...
     kernel:[  151.320857] bf00: 60000013 c0168538 00000000 00000000 00000000 c0255350 00000000 00000000
    
    Message from syslogd@89490200001095386101 at Mar 13 14:14:13 ...
     kernel:[  151.329391] bf20: c0233cb0 c017abcc c0a5eabb de012600 00000000 be86fc70 00000000 d4236480
    
    Message from syslogd@89490200001095386101 at Mar 13 14:14:13 ...
     kernel:[  151.337929] bf40: 00000128 c0107704 dca5a000 00000000 00067cc8 c05306ac 00000000 00000000
    
    Message from syslogd@89490200001095386101 at Mar 13 14:14:13 ...
     kernel:[  151.346463] bf60: 00000000 fffffff7 dca5beb0 0000000c 00000001 00000000 00000000 dca5be78
    
    Message from syslogd@89490200001095386101 at Mar 13 14:14:13 ...
     kernel:[  151.354990] bf80: 00000000 dca5a000 00000000 00000000 00000000 00000000 00097e58 00096c90
    
    Message from syslogd@89490200001095386101 at Mar 13 14:14:13 ...
     kernel:[  151.363521] bfa0: b6edb000 c0107560 00097e58 00096c90 00000005 be86fc70 00000000 00000000
    
    Message from syslogd@89490200001095386101 at Mar 13 14:14:13 ...
     kernel:[  151.372057] bfc0: 00097e58 00096c90 b6edb000 00000128 000303ad 00096e00 00097ba0 00067cc8
    
    Message from syslogd@89490200001095386101 at Mar 13 14:14:13 ...
     kernel:[  151.380596] bfe0: be86fc70 be86fc58 b6eccd17 b6cfaffc 40000010 00000005 9eff6861 9eff6c61
    
    Message from syslogd@89490200001095386101 at Mar 13 14:14:13 ...
     kernel:[  151.474929] Code: e3130010 1a000011 e0840105 e5903590 (e5932010) 
    [  156.641080] WILC_SPI spi1.2 wlan0: INFO [debug_thread]*** Debug Thread Running ***
    [  163.040175] WILC_SPI spi1.2 wlan0: INFO [debug_thread]*** Debug Thread Running ***
    [  169.440404] WILC_SPI spi1.2 wlan0: INFO [debug_thread]*** Debug Thread Running ***
    [  175.839809] WILC_SPI spi1.2 wlan0: INFO [debug_thread]*** Debug Thread Running ***
    [  182.240015] WILC_SPI spi1.2 wlan0: INFO [debug_thread]*** Debug Thread Running ***
    

After a while the device freezes stops responding and the console is flooded with this:

    [ 7882.740654] WILC_SPI spi1.2: Failed cmd response, cmd (cf), resp (00)
    [ 7882.747379] WILC_SPI spi1.2: Failed cmd reset
    [ 7882.751947] WILC_SPI spi1.2: Reset and retry 3 1 -568744354
    [ 7882.758913] WILC_SPI spi1.2: Failed cmd response, cmd (c3), resp (00)
    [ 7882.765662] WILC_SPI spi1.2: Failed cmd, write reg (00000001)...
    [ 7882.773086] WILC_SPI spi1.2: Failed cmd response, cmd (cf), resp (00)
    [ 7882.779808] WILC_SPI spi1.2: Failed cmd reset
    [ 7882.784376] WILC_SPI spi1.2: Reset and retry 2 1 -568744354
    [ 7882.791366] WILC_SPI spi1.2: Failed cmd response, cmd (c3), resp (00)
    [ 7882.798091] WILC_SPI spi1.2: Failed cmd, write reg (00000001)...
    [ 7882.805524] WILC_SPI spi1.2: Failed cmd response, cmd (cf), resp (00)

**Comment by AdhamAbozaeid** [comment]
Are you seeing the same behavior with the firmware binary posted here, with the driver from 15.2 (a65d074 )?

**Comment by tsifb** [comment]
@AdhamAbozaeid @Mateusz-Gwara we haven't tested AP mode yet (or AP+STA) I will try this sometime over the next few working days.
Also note we use sdio and are testing on kernel 4.14.73-linux4sam_6.0 whereas @Mateusz-Gwara is using spi.

Reliability seems to be good in STA mode.... no crashes / lockups seen so far.

**Comment by Mateusz-Gwara** [comment]
@AdhamAbozaeid 
I have 4 versions running now:

1.
- 4.9 kernel
- a65d074 driver
- dev firmware from 7.March 2019

2.
- 4.9 kernel
- a65d074 driver
- firmware from 5.March 2019 posted here

3.
- 4.14 kernel
- a65d074 driver
- dev firmware from 7.March 2019

4.
- 4.14 kernel
- a65d074 driver
- firmware from 5.March 2019 posted here

So far, the firmware posted here seems to be more stable. 
At least it does not show the errors I posted about the dev-branch firmware before.
