### ISSUE TITLE
Firmware for WiFi + Bluetooth?

### ISSUE THREAD

**Issue by shufps** [linux4wilc/firmware#8]
Is there a firmware which support Bluetooth and WiFi at the same time?

The specs from the module says:

"The ATWILC3000 utilizes highly optimized 802.11-Bluetooth coexistence protocols"

Coexistence only makes sense if WiFi and Bluetooth is used at the same time ... But where is the firmware for it?

Kind regards,
shupfs

**Comment by AdhamAbozaeid** [comment]
The current FW supports both Bluetooth and Wifi at the same time.
The two FW binaries runs together; one for Wifi and the other for Bluetooth since WILC3000 has dual CPUs

**Comment by rkashish75** [comment]
I would like to know, if we can scan nearby bluetooth devices and send the same over wi-fi simultaneously. I tried ESP32 but I found that it doesn't support simultaneous BT and WiFi. We can use only one at a time. Currently I'm using Arduino Mega with HC-05 and ESP01 ESP8266 to achieve simultaneous BT and WiFi, but there are three boards to handle. If ATWILC3000 supports both simultaneously, then my hardware is reduced.
Let me know

**Comment by ajaykathat** [comment]
>Can ATWILC3000 be used as a standalone unit for field deployment? or do I require one more MCU to monitor and collect data? I ordered one development board yesterday.

The ATWILC3000 should interface with a host. I assume you are planning to use WILC3000 with an MPU(Linux host). The WILC3000 module can be connected with a host over SPI or SDIO bus. We release precompiled images that have WILC3000 enabled for the Sama5d4Xplained host. The test image can be found at [WILC_DEMO](https://github.com/linux4wilc/wilc_demo/tree/master/wilc_sama5d4_linux_demo_5.10_kernel). The detail about [SAMA5D4 Xplained Board](https://www.microchip.com/en-us/development-tool/ATSAMA5D4-XULT) is available at [Link](https://www.linux4sam.org/bin/view/Linux4SAM/Sama5d4XplainedMainPage)
Alternatively, Microchip a ["SAMA5D27 WLSOM1"](https://www.microchip.com/en-us/development-tool/DM320117) evaluation kit that has integrated WILC3000 can be used for verification. The details related to the codebase, toolchain, compilation procedure, flashing tools, etc are available at [Sama5d27WLSom1EKMainPage](https://www.linux4sam.org/bin/view/Linux4SAM/Sama5d27WLSom1EKMainPage). Linux4Sam portal also has the precompiled images for SAMA5D27 WLSOM1 for quick verification.

> What tools will I require for its programming? 

The details are available at https://www.linux4sam.org/bin/view/Linux4SAM

>can you share a sample code for using the Wifi and BT? 

WiFi & BT sample applications are available at https://www.linux4sam.org/bin/view/Linux4SAM/Applications#WiFi_and_Bluetooth

**Comment by rkashish75** [comment]
Thanks for the reply Ajay.
I think ATWILC3000 supports communication with Arduino as well?
Linux Host means raspberry Pi for field deployment?
Let me know.
*- Thanks & Regards,*
*Ashish R. Kulkarni*
*SMIEEE, MIE(India)*
Asst. Professor in Electrical Engineering,

*Delhi Technological University, Delhi(Formerly Delhi College of Engg.,)*
*Main Bawana Road, Shahbad Daulatpur*

*Delhi - 110042 (INDIA)*Ph. +919013281975(M) 9821158381, 01127871047 (O)
***@***.***, ***@***.***

**Comment by ajaykathat** [comment]
>I think ATWILC3000 supports communication with Arduino as well?

Yes

 >Linux Host means raspberry Pi for field deployment? 

Yes, WILC3000 can be connected to raspberry Pi.

**Comment by rkashish75** [comment]
Hello Ajay,
I have received the ATWILC3000 board.
I got one document on how to use ATWILC3000, but it is for Linux machine. I
need help on getting started with Arduino. As I can see, the ATWILC3000
shield is perfectly compatible with Arduino. I have  a Mega and a Uno with
me.
Can you help me to get started with this?
*- Thanks & Regards,*
*Ashish R. Kulkarni*
*SMIEEE, MIE(India)*
Asst. Professor in Electrical Engineering,

*Delhi Technological University, Delhi(Formerly Delhi College of Engg.,)*
*Main Bawana Road, Shahbad Daulatpur*

*Delhi - 110042 (INDIA)*Ph. +919013281975(M) 9821158381, 01127871047 (O)
***@***.***, ***@***.***

**Comment by ajaykathat** [comment]
The ATWILC3000 board can be connected with a Linux host as well as using Advanced Software Framework (ASF) for SAM Devices. This GitHub contains the firmware which is required for a Linux host but for ASF the setup is different. I could find one sample WIFI [example](https://www.mouser.com/datasheet/2/268/AVR-IoT-WG-Development-Board-User-Guide-50002809B-1859397.pdf) demo app that uses Atmeg4808 along with WILC1500 though it is not the same as yours setup. For any other help on ASF setup, I suggest to please raise a [salesForce](https://microchipsupport.force.com/s/) ticket. The support team would be able to help you with the setup and combination to use with WILC3000.

Regards,
Ajay

**Comment by rkashish75** [comment]
Thanks a lot, Ajay.
I'll go thru the resources and also raise a salesforce ticket.
Thanks once again.
*- Thanks & Regards,*
*Ashish R. Kulkarni*
*SMIEEE, MIE(India)*
Asst. Professor in Electrical Engineering,

*Delhi Technological University, Delhi(Formerly Delhi College of Engg.,)*
*Main Bawana Road, Shahbad Daulatpur*

*Delhi - 110042 (INDIA)*Ph. +919013281975(M) 9821158381, 01127871047 (O)
***@***.***, ***@***.***
